include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # ignore json key annotations used in freezed constructors
    invalid_annotation_target: ignore
    unused_import: error
    use_build_context_synchronously: error
    file_names: error
    prefer_const_constructors: error
    prefer_const_declarations: error
    body_might_complete_normally_nullable: warning
    unnecessary_import: error
    unused_local_variable: error
    unused_element: error
    unused_catch_clause: error
    unused_result: error
    unused_field: error
    avoid_empty_else: error
    avoid_unused_constructor_parameters: error
    avoid_print: warning

linter:
  rules:
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
