name: ricknotmorty
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  app_links: ^6.4.0
  auto_route: ^9.3.0+1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  dartz: ^0.10.1
  device_info_plus: 11.3.0
  dio: ^5.8.0+1
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^19.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_api_availability: ^5.0.1
  graphql: ^5.2.0
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  lottie: ^3.3.1
  path: ^1.9.0
  permission_handler: ^11.4.0
  pretty_dio_logger: ^1.4.0
  protect_app: ^0.0.5
  shared_preferences: ^2.5.2
  sqflite: ^2.4.0
  store_checker: ^1.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  mocktail: ^1.0.4



flutter:

  uses-material-design: true

  assets:
     - lib/i18n/
     - assets/
     - assets/lottie/   

